plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.example.cashtrack"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.example.cashtrack"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {

    // --- Android core libraries ---
    implementation(libs.appcompat)
    implementation(libs.activity)
    implementation(libs.constraintlayout)

    // --- Material Design Components (UI widgets, themes, etc) ---
    implementation("com.google.android.material:material:1.12.0")

    // --- Charts and Graphs ---
    implementation("com.github.PhilJay:MPAndroidChart:v3.1.0")

    // --- Testing libraries (auto-generated by Android Studio) ---
    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
}
